### ISSUE TITLE
No package.json

### ISSUE THREAD

**Issue by zertyz** [lexcaraig/angular-setup#1]
Hi, Lex.

Thank you for the tutorial.

Is this project meant to be a starter? Or am I missing something?

-- Luiz.

**Comment by lexcaraig** [comment]
Hi @zerty, yes, this is meant to be a starter but basically after generating an angular project via angular-cli. 

So after you generate a new project you’ll just have to download the folders from here and paste it to your project and follow the instructions in README.MD. After that you are good to go. 

This project is intented to be ready to use in any version of angular.

**Comment by lexcaraig** [comment]
Hi @zertyz, regarding on your concern, I did create an example application implementing these structures that I've made, so you just have to download or clone. It is located at the `example-app` folder. After cloning you should be good to go and up and running. :)

You just have to update some files from default.
